<?php
/**
 * SFP Page Config - FAQ Schema Fix
 *
 * Fixes broken FAQPage JSON-LD structured data generated by Spectra's
 * FAQ block (uagb/faq) when FAQ answers contain HTML with class
 * attributes. Spectra dumps raw innerHTML into a JSON string value
 * without escaping the double quotes in HTML attributes, which breaks
 * the JSON at the first class="..." occurrence.
 *
 * This filter intercepts the rendered block output, detects broken
 * JSON-LD, and rebuilds it from the HTML content of the FAQ block
 * (Strategy A: DOM rebuild). This is more robust than trying to
 * repair the broken JSON string.
 *
 * Only affects JSON-LD within FAQ block output in the page body.
 * SureRank schema in <head> is not touched.
 *
 * @package SFP_Page_Config
 * @since   2.5.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_filter( 'render_block_uagb/faq', 'sfp_page_config_fix_faq_schema', 10, 2 );

/**
 * Filter the rendered output of Spectra FAQ blocks to fix broken
 * FAQPage JSON-LD structured data.
 *
 * @param  string $block_content The block's rendered HTML.
 * @param  array  $block         The parsed block data.
 * @return string                Fixed HTML.
 */
function sfp_page_config_fix_faq_schema( $block_content, $block ) {

    // Bail early if there is no FAQPage schema in this block's output.
    if ( strpos( $block_content, 'FAQPage' ) === false ) {
        return $block_content;
    }

    // Find and process each JSON-LD script tag in the block output.
    $block_content = preg_replace_callback(
        '/<script\s+type=["\']application\/ld\+json["\']>(.*?)<\/script>/s',
        function ( $matches ) use ( $block_content ) {
            return sfp_page_config_repair_faq_json( $matches, $block_content );
        },
        $block_content
    );

    return $block_content;
}

/**
 * Attempt to repair a single JSON-LD script tag from a FAQ block.
 *
 * If the JSON is already valid, it is returned unchanged.
 * If broken, the FAQPage schema is rebuilt from the HTML content
 * of the FAQ block.
 *
 * @param  array  $matches       Regex matches: [0] = full script tag, [1] = JSON content.
 * @param  string $block_content The full block HTML (used to extract Q&A from DOM).
 * @return string                The (possibly repaired) script tag.
 */
function sfp_page_config_repair_faq_json( $matches, $block_content ) {

    $raw = $matches[1];

    // If JSON is already valid, leave it alone.
    $decoded = json_decode( $raw, true );
    if ( json_last_error() === JSON_ERROR_NONE ) {
        return $matches[0];
    }

    // JSON is broken. Rebuild from the HTML.
    $qa_pairs = sfp_page_config_extract_faq_from_html( $block_content );

    if ( empty( $qa_pairs ) ) {
        // Could not extract Q&A pairs. Log and return original.
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log(
                'SFP Page Config: FAQ schema repair failed - could not extract Q&A pairs from block HTML. '
                . 'Post ID: ' . get_queried_object_id()
            );
        }
        return $matches[0];
    }

    // Build clean FAQPage schema.
    $schema = array(
        '@context'   => 'https://schema.org',
        '@type'      => 'FAQPage',
        'mainEntity' => array(),
    );

    foreach ( $qa_pairs as $pair ) {
        $schema['mainEntity'][] = array(
            '@type'          => 'Question',
            'name'           => $pair['question'],
            'acceptedAnswer' => array(
                '@type' => 'Answer',
                'text'  => $pair['answer'],
            ),
        );
    }

    $json = wp_json_encode( $schema, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );

    if ( ! $json ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log(
                'SFP Page Config: FAQ schema repair failed - wp_json_encode returned false. '
                . 'Post ID: ' . get_queried_object_id()
            );
        }
        return $matches[0];
    }

    return '<script type="application/ld+json">' . $json . '</script>';
}

/**
 * Extract question/answer pairs from FAQ block HTML.
 *
 * Parses the block HTML to find Spectra FAQ items and extracts the
 * question text and answer text (HTML-stripped for schema purposes).
 *
 * @param  string $html The full FAQ block HTML.
 * @return array        Array of ['question' => '...', 'answer' => '...'] pairs.
 */
function sfp_page_config_extract_faq_from_html( $html ) {

    $qa_pairs = array();

    // Use DOMDocument for robust HTML parsing.
    $doc = new DOMDocument();

    // Suppress warnings from malformed HTML. Prefix with XML encoding
    // declaration to handle UTF-8 correctly.
    $prev = libxml_use_internal_errors( true );
    $doc->loadHTML(
        '<?xml encoding="UTF-8">' . $html,
        LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
    );
    libxml_clear_errors();
    libxml_use_internal_errors( $prev );

    $xpath = new DOMXPath( $doc );

    // Spectra FAQ structure:
    // .uagb-faq-child wraps each Q&A pair.
    // .uagb-question contains the question text.
    // .uagb-faq-content contains the answer HTML.
    $faq_items = $xpath->query( '//*[contains(@class, "uagb-faq-child")]' );

    if ( $faq_items->length === 0 ) {
        // Fallback: try matching question/answer elements directly.
        $questions = $xpath->query( '//*[contains(@class, "uagb-question")]' );
        $answers   = $xpath->query( '//*[contains(@class, "uagb-faq-content")]' );

        if ( $questions->length === 0 || $answers->length === 0 ) {
            return array();
        }

        $count = min( $questions->length, $answers->length );
        for ( $i = 0; $i < $count; $i++ ) {
            $q_text = trim( $questions->item( $i )->textContent );
            $a_text = sfp_page_config_get_schema_safe_text( $answers->item( $i ), $doc );

            if ( $q_text && $a_text ) {
                $qa_pairs[] = array(
                    'question' => $q_text,
                    'answer'   => $a_text,
                );
            }
        }

        return $qa_pairs;
    }

    foreach ( $faq_items as $item ) {
        $question_nodes = $xpath->query( './/*[contains(@class, "uagb-question")]', $item );
        $answer_nodes   = $xpath->query( './/*[contains(@class, "uagb-faq-content")]', $item );

        if ( $question_nodes->length === 0 || $answer_nodes->length === 0 ) {
            continue;
        }

        $q_text = trim( $question_nodes->item( 0 )->textContent );
        $a_text = sfp_page_config_get_schema_safe_text( $answer_nodes->item( 0 ), $doc );

        if ( $q_text && $a_text ) {
            $qa_pairs[] = array(
                'question' => $q_text,
                'answer'   => $a_text,
            );
        }
    }

    return $qa_pairs;
}

/**
 * Get schema-safe text content from a DOM node.
 *
 * Strips HTML tags but preserves line breaks as plain text.
 * Google accepts plain text with <br> in FAQ schema answers.
 *
 * @param  DOMNode     $node The DOM node to extract text from.
 * @param  DOMDocument $doc  The parent document.
 * @return string            Cleaned text suitable for JSON-LD.
 */
function sfp_page_config_get_schema_safe_text( $node, $doc ) {

    // Get the inner HTML of the node.
    $inner_html = '';
    foreach ( $node->childNodes as $child ) {
        $inner_html .= $doc->saveHTML( $child );
    }

    // Strip all HTML tags. wp_strip_all_tags also handles script/style.
    $text = wp_strip_all_tags( $inner_html );

    // Collapse multiple whitespace/newlines into single spaces.
    $text = preg_replace( '/\s+/', ' ', $text );

    return trim( $text );
}
